### ISSUE TITLE
Disconnection reason doesn't translate

### ISSUE THREAD

**Issue by NikitaCartes** [arthurbambou/Server-Translations#20]
![example](https://user-images.githubusercontent.com/18899227/138185918-a20cf925-1230-497e-9ebd-98251625b366.gif)

I made the littlest mod that reproduce that bug: https://github.com/NikitaCartes-forks/TranslationBugExample

Basically it's just:
```
@Mixin(PlayerManager.class)
public abstract class PlayerManagerMixin {

    @Inject(method = "checkCanJoin(Ljava/net/SocketAddress;Lcom/mojang/authlib/GameProfile;)Lnet/minecraft/text/Text;", at = @At("HEAD"), cancellable = true)
    private void checkCanJoin(SocketAddress socketAddress, GameProfile profile, CallbackInfoReturnable<Text> cir) {
        TranslatableText returnText = new TranslatableText("text.bugexample.bugexample");
        cir.setReturnValue(returnText);
    }
}
```

**Comment by arthurbambou** [comment]
This should be fixed in newer versions I think

**Comment by NikitaCartes** [comment]
I updated my mod to 1.18.2 but it's still doesn't translated
